name: Watch for new release elsewhere
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_IMAGE_NAME: ${{ vars.FRONTEND_IMAGE_NAME }}  # image name on Docker Hub
  GITHUB_REPO: ${{ vars.FRONTEND_REPO }}    # repo to watch for releases
on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  workflow_dispatch:      # allow manual runs

jobs:
  watch-release:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check latest release
        id: check-release
        run: |
          repo=${{ env.GITHUB_REPO }}
          latest_tag=$(curl -s "https://api.github.com/repos/${{ env.GITHUB_REPO }}/tags" | \
            jq -r '.[0].name')
          echo "latest=$latest_tag" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        if: steps.check-release.outputs.exists != 'true'
        with:
            repository: ${{ env.GITHUB_REPO }}
            ref: ${{ steps.check-release.outputs.latest }}



      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: steps.check-release.outputs.exists != 'true'
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.check-release.outputs.exists != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags)
        if: steps.check-release.outputs.exists != 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}

      # now lets examine the metadata output to see if the tag already exists, if not we will build and push the image
      # search for the tag in the metadata output, if it exists we will skip the build and push steps
      - name: Debug metadata output
        id: check-tag
        if: steps.check-release.outputs.exists != 'true'
        run: |
          if [ grep -q "${{ steps.meta.outputs.latest }}" <<< "${{ steps.meta.outputs.tags }}" ]; then
            echo "Tag already exists in metadata output, skipping build and push."
            echo "found=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist in metadata output, proceeding with build and push."
            echo "found=false" >> $GITHUB_ENV
          fi
      - name: Build and push ARM64 image
        if: steps.check-tag.outputs.found == 'false'
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ steps.check-release.outputs.latest }}